try { require('dotenv').config(); } catch (e) { /* Render usa variáveis de ambiente; dotenv é opcional */ }
const express=require('express');
const cors=require('cors');
const bcrypt=require('bcryptjs');
const multer=require('multer');
const pdfParse=require('pdf-parse');
const {createClient}=require('@supabase/supabase-js');
const app=express();
app.use(cors()); app.use(express.json({limit:'50mb'})); app.use(express.static('public'));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024}});
const PORT=process.env.PORT||3000;
const supabaseUrl=process.env.SUPABASE_URL; const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_ANON_KEY;
const supabase=(supabaseUrl&&serviceKey)?createClient(supabaseUrl,serviceKey):null;
const allowed=['produtos','clientes','receitas','receita_itens','pedidos','pedido_itens','vendas','venda_itens','financeiro','pro_labore','campanhas_whatsapp','usuarios','configuracoes','producoes','arquivos_receitas','fornecedores','compras','compra_itens','estoque_movimentos'];
const searchCols={produtos:'nome',clientes:'nome',receitas:'nome',pedidos:'cliente_nome',usuarios:'nome',campanhas_whatsapp:'nome',financeiro:'descricao',producoes:'descricao',fornecedores:'nome',compras:'numero_nf'};
const money=n=>Number(n||0); const upper=v=>typeof v==='string'?v.trim().toUpperCase():v;
function normalize(o){ if(!o||typeof o!=='object')return o; const keepCase=['senha','senha_hash','apiKey','url','texto_extraido','modo_preparo','observacoes','mensagem','permissoes']; for(const k of Object.keys(o)){ if(keepCase.includes(k)) continue; if(typeof o[k]==='string') o[k]=upper(o[k]); } return o; }
function ok(res,data){res.json({ok:true,data})} function fail(res,e,c=500){res.status(c).json({ok:false,error:e.message||String(e)})} function db(res){if(!supabase){fail(res,'Supabase não configurado. Configure SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY no Render.',400);return false}return true}
async function getConfig(chave){ if(!supabase) return null; const r=await supabase.from('configuracoes').select('*').eq('chave',chave).maybeSingle(); return r.data?.valor||null; }
async function setConfig(chave,valor){ const r=await supabase.from('configuracoes').upsert({chave,valor},{onConflict:'chave'}).select().single(); if(r.error) throw r.error; return r.data; }
async function evo(){ const cfg=await getConfig('whatsapp'); return {url:cfg?.url||process.env.EVOLUTION_API_URL||'', apiKey:cfg?.apiKey||process.env.EVOLUTION_API_KEY||'', instance:cfg?.instance||process.env.EVOLUTION_INSTANCE||'confeitaria'}; }
async function evoFetch(path,opt={}){ const c=await evo(); if(!c.url||!c.apiKey||!c.instance) throw new Error('Configure WhatsApp em CONFIGURAÇÕES > WHATSAPP.'); const url=c.url.replace(/\/$/,'')+path.replace('{instance}',encodeURIComponent(c.instance)); const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json','apikey':c.apiKey,...(opt.headers||{})}}); const txt=await r.text(); let data; try{data=JSON.parse(txt)}catch{data=txt} if(!r.ok) throw new Error(typeof data==='string'?data:(data.message||data.error||'Erro Evolution API')); return data; }
app.get('/api/health',(_,res)=>ok(res,{app:'CONFEITARIA OLITECH ERP',version:'5.5.0',supabase:!!supabase}));
app.post('/api/login',async(req,res)=>{try{if(!db(res))return; const {usuario,senha}=req.body; const {data,error}=await supabase.from('usuarios').select('*').eq('usuario',String(usuario||'').toLowerCase()).eq('ativo',true).maybeSingle(); if(error)throw error; if(!data)return fail(res,'Usuário não encontrado ou bloqueado.',401); const hashOk=data.senha_hash?await bcrypt.compare(senha,data.senha_hash):false; const legacyOk=!data.senha_hash&&data.senha===senha; if(!hashOk&&!legacyOk)return fail(res,'Senha inválida.',401); ok(res,{id:data.id,nome:data.nome,usuario:data.usuario,perfil:data.perfil,permissoes:data.permissoes||{todas:data.perfil==='admin'}})}catch(e){fail(res,e)}});
app.get('/api/:table',async(req,res)=>{try{if(!db(res))return; const t=req.params.table; if(t==='formas-pagamento-v2'){ const c=await getConfig('formas_pagamento'); let formas=c?.formas||defaultFormasPagamento(); formas=formas.map(normForma); return ok(res,formas); } if(t==='formas-pagamento'){ const c=await getConfig('formas_pagamento'); return ok(res,c?.formas||['DINHEIRO','PIX','DÉBITO','CRÉDITO','CREDIÁRIO']); } if(!allowed.includes(t))return fail(res,'Tabela inválida',400); let q=supabase.from(t).select('*').order('created_at',{ascending:false}); const busca=(req.query.busca||'').trim(); if(busca&&searchCols[t]) q=q.ilike(searchCols[t],`%${busca}%`); const {data,error}=await q.limit(Number(req.query.limit||1000)); if(error)throw error; ok(res,data)}catch(e){fail(res,e)}});
app.post('/api/:table',async(req,res)=>{try{if(!db(res))return; const t=req.params.table; if(t==='formas-pagamento-v2'){ let formas=(req.body.formas||[]).map(normForma).filter(f=>f.nome); if(!formas.length) formas=defaultFormasPagamento(); return ok(res,await setConfig('formas_pagamento',{formas})); } if(t==='formas-pagamento'){ let formas=(req.body.formas||[]).map(upper).filter(Boolean); if(!formas.length) formas=['DINHEIRO','PIX','DÉBITO','CRÉDITO','CREDIÁRIO']; return ok(res,await setConfig('formas_pagamento',{formas})); } if(!allowed.includes(t))return fail(res,'Tabela inválida',400); let body=normalize(req.body||{}); if(t==='usuarios'&&body.senha){body.usuario=String(body.usuario||'').toLowerCase(); body.senha_hash=await bcrypt.hash(body.senha,10); delete body.senha} if(t==='produtos') calcProduto(body); const {data,error}=await supabase.from(t).upsert(body).select().single(); if(error)throw error; ok(res,data)}catch(e){fail(res,e)}});
app.delete('/api/:table/:id',async(req,res)=>{try{if(!db(res))return; const t=req.params.table; if(!allowed.includes(t))return fail(res,'Tabela inválida',400); if(t==='produtos' && String(req.query.force||'')!=='true'){ const refs=await supabase.from('receita_itens').select('id,receita_id').eq('produto_id',req.params.id).limit(5); if(refs.error) throw refs.error; if((refs.data||[]).length){ return fail(res,'PRODUTO VINCULADO A RECEITA. SE EXCLUIR, A RECEITA FICARÁ INCOMPLETA. CONFIRME NOVAMENTE PARA PROSSEGUIR.',409); }} const {error}=await supabase.from(t).delete().eq('id',req.params.id); if(error)throw error; ok(res,{deleted:true})}catch(e){fail(res,e)}});
function calcProduto(p){ const custo=money(p.custo_unitario||p.custo_medio||0), venda=money(p.preco_venda||0), margem=money(p.margem_percentual||0); if(custo&&margem&&!venda) p.preco_venda=+(custo*(1+margem/100)).toFixed(2); if(custo&&venda&&!margem) p.margem_percentual=+(((venda-custo)/custo)*100).toFixed(2); return p; }
app.post('/api/produtos/calcular-preco',async(req,res)=>{try{ok(res,calcProduto(req.body||{}))}catch(e){fail(res,e)}});
app.get('/api/dashboard/resumo',async(_,res)=>{try{if(!db(res))return; const hoje=new Date().toISOString().slice(0,10); const am=new Date(Date.now()+86400000).toISOString().slice(0,10); const [pedH,pedA,prod,ven,fin,rec]=await Promise.all([supabase.from('pedidos').select('*').eq('data_entrega',hoje).order('hora_entrega'),supabase.from('pedidos').select('*').eq('data_entrega',am).order('hora_entrega'),supabase.from('produtos').select('*'),supabase.from('vendas').select('*').gte('created_at',hoje+'T00:00:00'),supabase.from('financeiro').select('*').eq('status','ABERTO'),supabase.from('receitas').select('*')]); [pedH,pedA,prod,ven,fin,rec].forEach(r=>{if(r.error)throw r.error}); ok(res,{pedidosHoje:pedH.data,pedidosAmanha:pedA.data,alertasEstoque:prod.data.filter(p=>money(p.estoque_atual)<=money(p.estoque_minimo)),faturamentoHoje:ven.data.reduce((s,v)=>s+money(v.total),0),financeiroAberto:fin.data,receitas:rec.data.length,produtos:prod.data.length})}catch(e){fail(res,e)}});
app.post('/api/compras/lancar',async(req,res)=>{try{if(!db(res))return; const body=normalize(req.body||{}); const itens=body.itens||[]; delete body.itens; const {data:compra,error}=await supabase.from('compras').insert(body).select().single(); if(error)throw error; let total=0; for(const raw of itens){const it=normalize({...raw,compra_id:compra.id}); it.total=money(it.quantidade)*money(it.valor_unitario); total+=it.total; const ins=await supabase.from('compra_itens').insert(it); if(ins.error) throw ins.error; if(it.produto_id){ const p=await supabase.from('produtos').select('*').eq('id',it.produto_id).single(); if(!p.error){ const qtdAnt=money(p.data.estoque_atual), custoMed=money(p.data.custo_medio||p.data.custo_unitario), qtdComp=money(p.data.quantidade_compras); const novoEst=qtdAnt+money(it.quantidade); const novoQtdComp=qtdComp+1; const custoMedNovo=novoQtdComp>=3?(((custoMed*Math.max(qtdAnt,0))+(money(it.valor_unitario)*money(it.quantidade)))/Math.max(novoEst,1)):custoMed; const upd={estoque_atual:novoEst,ultima_compra_valor:money(it.valor_unitario),ultima_compra_data:body.data_compra||new Date().toISOString().slice(0,10),quantidade_compras:novoQtdComp}; if(novoQtdComp>=3) upd.custo_medio=+custoMedNovo.toFixed(4); upd.custo_unitario=upd.custo_medio||money(it.valor_unitario); calcProduto(upd); await supabase.from('produtos').update(upd).eq('id',it.produto_id); await supabase.from('estoque_movimentos').insert({produto_id:it.produto_id,tipo:'ENTRADA',origem:'COMPRA',quantidade:it.quantidade,valor_unitario:it.valor_unitario,referencia:compra.id}); } } }
 await supabase.from('compras').update({total}).eq('id',compra.id); ok(res,{compra:{...compra,total},itens,total})}catch(e){fail(res,e)}});
app.post('/api/receitas/calcular',async(req,res)=>{try{if(!db(res))return; const {receita_id,peso_base=1,peso_desejado=1,margem_percentual=100,preco_venda}=req.body; const receita=await supabase.from('receitas').select('*').eq('id',receita_id).single(); if(receita.error)throw receita.error; const itens=await supabase.from('receita_itens').select('*, produtos(*)').eq('receita_id',receita_id); if(itens.error)throw itens.error; const fator=money(peso_desejado)/money(peso_base||receita.data.peso_base||1); const detalhes=itens.data.map(i=>{const qtd=money(i.quantidade)*fator; const custoUnit=money(i.custo_unitario||i.produtos?.custo_medio||i.produtos?.custo_unitario); return {produto:i.produtos?.nome||i.descricao,unidade:i.unidade,quantidade:+qtd.toFixed(3),custo_unitario:custoUnit,custo_total:+(qtd*custoUnit).toFixed(2)}}); const custo=detalhes.reduce((s,i)=>s+i.custo_total,0); const venda=preco_venda?money(preco_venda):custo*(1+money(margem_percentual)/100); ok(res,{receita:receita.data,peso_desejado,fator,custo:+custo.toFixed(2),venda:+venda.toFixed(2),margem:custo?+(((venda-custo)/custo)*100).toFixed(2):0,detalhes})}catch(e){fail(res,e)}});
app.post('/api/producao/baixar-estoque',async(req,res)=>{try{if(!db(res))return; const {receita_id,peso_base=1,peso_desejado=1,descricao='PRODUÇÃO',responsavel=''}=normalize(req.body); const calcReq=await fetch(`http://127.0.0.1:${PORT}/api/receitas/calcular`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({receita_id,peso_base,peso_desejado})}).then(r=>r.json()); const calc=calcReq.data; for(const it of calc.detalhes){ const prod=await supabase.from('produtos').select('*').eq('nome',it.produto).maybeSingle(); if(prod.data){ await supabase.from('produtos').update({estoque_atual:money(prod.data.estoque_atual)-money(it.quantidade)}).eq('id',prod.data.id); await supabase.from('estoque_movimentos').insert({produto_id:prod.data.id,tipo:'SAIDA',origem:'PRODUCAO',quantidade:it.quantidade,valor_unitario:it.custo_unitario}); }} const {data,error}=await supabase.from('producoes').insert({receita_id,peso_desejado,descricao,responsavel,status:'PRODUZIDO',custo_total:calc.custo}).select().single(); if(error)throw error; ok(res,{producao:data,calculo:calc})}catch(e){fail(res,e)}});
app.post('/api/receitas/importar-pdf',upload.single('pdf'),async(req,res)=>{try{if(!db(res))return; if(!req.file)throw new Error('Envie um PDF.'); const parsed=await pdfParse(req.file.buffer); const text=(parsed.text||'').slice(0,40000); const nome=upper(req.body.nome||req.file.originalname.replace(/\.pdf$/i,'')); const r=await supabase.from('receitas').insert({nome,categoria:upper(req.body.categoria||'IMPORTADA PDF'),modo_preparo:text,peso_base:1,unidade_base:'RECEITA',rendimento:'IMPORTADO DE PDF'}).select().single(); if(r.error)throw r.error; await supabase.from('arquivos_receitas').insert({receita_id:r.data.id,nome_arquivo:req.file.originalname,tipo:req.file.mimetype,texto_extraido:text}); ok(res,{receita:r.data,caracteres:text.length})}catch(e){fail(res,e)}});
app.get('/api/prolabore/resumo',async(req,res)=>{try{if(!db(res))return; let qv=supabase.from('vendas').select('*'); let qf=supabase.from('financeiro').select('*').eq('status','PAGO'); let qp=supabase.from('pro_labore').select('*'); const {inicio,fim}=req.query; if(inicio){qv=qv.gte('created_at',inicio+'T00:00:00');qf=qf.gte('pagamento',inicio);qp=qp.gte('data_referencia',inicio)} if(fim){qv=qv.lte('created_at',fim+'T23:59:59');qf=qf.lte('pagamento',fim);qp=qp.lte('data_referencia',fim)} const [v,f,p]=await Promise.all([qv,qf,qp]); [v,f,p].forEach(r=>{if(r.error)throw r.error}); const entradas=v.data.reduce((s,i)=>s+money(i.total),0)+f.data.filter(i=>i.tipo==='RECEITA').reduce((s,i)=>s+money(i.valor),0); const saidas=f.data.filter(i=>i.tipo==='DESPESA').reduce((s,i)=>s+money(i.valor),0); const retiradas=p.data.reduce((s,i)=>s+money(i.valor),0); ok(res,{entradas,saidas,caixa:entradas-saidas,retiradas,disponivel:entradas-saidas-retiradas,pro_labore:p.data})}catch(e){fail(res,e)}});
app.post('/api/config/whatsapp',async(req,res)=>{try{if(!db(res))return; const atual=await getConfig('whatsapp')||{}; const body={...atual,...(req.body||{})}; if(!body.apiKey || String(body.apiKey).startsWith('********')) body.apiKey=atual.apiKey||''; ok(res,await setConfig('whatsapp',body))}catch(e){fail(res,e)}});
app.get('/api/config/whatsapp',async(_,res)=>{try{if(!db(res))return; const c=await evo(); ok(res,{url:c.url,instance:c.instance,apiKey:c.apiKey?'********'+c.apiKey.slice(-4):''})}catch(e){fail(res,e)}});
app.get('/api/whatsapp/qrcode',async(_,res)=>{try{let data; try{data=await evoFetch('/instance/connect/{instance}')}catch(e){data=await evoFetch('/instance/qrcode/{instance}')} const qr=data?.base64||data?.qrcode?.base64||data?.code||data?.qrcode||data; ok(res,{qrcode:typeof qr==='string'?qr:null,raw:data,instrucoes:'LEIA O QR CODE PELO WHATSAPP PARA CONECTAR OU TROCAR NÚMERO.'})}catch(e){fail(res,e)}});
app.post('/api/whatsapp/campanhas/enviar',async(req,res)=>{try{if(!db(res))return; const campanha=normalize({...req.body,status:req.body.enviar_agora?'ENVIANDO':'PROGRAMADA',enviados:0,entregues:0,falhas:0}); const {data,error}=await supabase.from('campanhas_whatsapp').upsert(campanha).select().single(); if(error)throw error; ok(res,{campanha:data,mensagem:'CAMPANHA SALVA.'})}catch(e){fail(res,e)}});
app.get('/api/backup/exportar',async(_,res)=>{try{if(!db(res))return; const backup={versao:'4.0.0',gerado_em:new Date().toISOString(),tabelas:{}}; for(const t of allowed){const {data,error}=await supabase.from(t).select('*').limit(10000); backup.tabelas[t]=error?[]:data} ok(res,backup)}catch(e){fail(res,e)}});
app.post('/api/backup/restaurar',upload.single('backup'),async(req,res)=>{try{if(!db(res))return; if(!req.file)throw new Error('Selecione um JSON de backup.'); const backup=JSON.parse(req.file.buffer.toString('utf8')); const resumo={}; for(const t of allowed){const rows=backup.tabelas?.[t]||backup[t]||[]; if(!rows.length)continue; const {error}=await supabase.from(t).upsert(rows); if(error)throw error; resumo[t]=rows.length} ok(res,{resumo})}catch(e){fail(res,e)}});


// ===== V4.3 - CLIENTES IMPORT/EXPORT, LOGO, CAMPANHAS COM ANEXOS E VENDAS =====
function onlyDigits(v){return String(v||'').replace(/\D/g,'')}
function csvEscape(v){v=v==null?'':String(v); return /[;"\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function parseCSV(txt){
  const lines=txt.replace(/^\uFEFF/,'').split(/\r?\n/).filter(l=>l.trim());
  if(!lines.length) return [];
  const sep=lines[0].includes(';')?';':',';
  const head=lines[0].split(sep).map(h=>h.trim().toLowerCase());
  return lines.slice(1).map(line=>{const cols=line.split(sep); const o={}; head.forEach((h,i)=>o[h]=cols[i]||''); return o;});
}
async function getLogo(){return await getConfig('empresa')||{};}
app.get('/api/config/empresa',async(_,res)=>{try{if(!db(res))return; ok(res,await getLogo())}catch(e){fail(res,e)}});
app.post('/api/config/empresa',upload.single('logo'),async(req,res)=>{try{if(!db(res))return; const atual=await getLogo(); const body=normalize(req.body||{}); if(req.file){body.logo_data='data:'+req.file.mimetype+';base64,'+req.file.buffer.toString('base64'); body.logo_nome=req.file.originalname;} ok(res,await setConfig('empresa',{...atual,...body}))}catch(e){fail(res,e)}});
app.get('/api/clientes/exportar',async(_,res)=>{try{if(!db(res))return; const {data,error}=await supabase.from('clientes').select('*').order('nome'); if(error)throw error; const cols=['nome','telefone','whatsapp','email','cpf_cnpj','rua','numero','complemento','bairro','cidade','estado','cep','observacoes']; const csv=[cols.join(';')].concat((data||[]).map(r=>cols.map(c=>csvEscape(r[c])).join(';'))).join('\n'); res.setHeader('Content-Type','text/csv; charset=utf-8'); res.setHeader('Content-Disposition','attachment; filename="clientes-confeitaria-olitech.csv"'); res.send('\ufeff'+csv)}catch(e){fail(res,e)}});
app.post('/api/clientes/importar',upload.single('arquivo'),async(req,res)=>{try{if(!db(res))return; if(!req.file)throw new Error('Selecione CSV exportado dos contatos do celular.'); const rows=parseCSV(req.file.buffer.toString('utf8')); let okCount=0; for(const r of rows){ const nome=upper(r.nome||r.name||r['display name']||r.cliente); const tel=r.whatsapp||r.telefone||r.phone||r['mobile phone']||r.celular||''; if(!nome&&!tel) continue; const row=normalize({nome:nome||tel,telefone:tel,whatsapp:tel,email:r.email||r['e-mail']||'',cpf_cnpj:r.cpf_cnpj||r.cnpj||r.cpf||'',rua:r.rua||r.endereco||'',numero:r.numero||'',bairro:r.bairro||'',cidade:r.cidade||'',estado:r.estado||'',cep:r.cep||'',observacoes:r.observacoes||'IMPORTADO'}); const existing=onlyDigits(tel); let q=supabase.from('clientes').select('id').limit(1); if(existing) q=q.or(`telefone.ilike.%${existing}%,whatsapp.ilike.%${existing}%`); else q=q.eq('nome',row.nome); const e=await q.maybeSingle(); if(e.data?.id) row.id=e.data.id; const ins=await supabase.from('clientes').upsert(row).select().single(); if(!ins.error) okCount++; } ok(res,{importados:okCount,total:rows.length})}catch(e){fail(res,e)}});
app.post('/api/vendas/cancelar/:id',async(req,res)=>{try{if(!db(res))return; const {motivo='CANCELADA'}=normalize(req.body||{}); const {data,error}=await supabase.from('vendas').update({status:'CANCELADA',motivo_cancelamento:motivo,cancelada_em:new Date().toISOString()}).eq('id',req.params.id).select().single(); if(error)throw error; ok(res,data)}catch(e){fail(res,e)}});
app.get('/api/formas-pagamento',async(_,res)=>{try{if(!db(res))return; const c=await getConfig('formas_pagamento'); ok(res,c?.formas||['DINHEIRO','PIX','DÉBITO','CRÉDITO','CREDIÁRIO'])}catch(e){fail(res,e)}});
app.post('/api/formas-pagamento',async(req,res)=>{try{if(!db(res))return; let formas=(req.body.formas||[]).map(upper).filter(Boolean); if(!formas.length) formas=['DINHEIRO','PIX','DÉBITO','CRÉDITO','CREDIÁRIO']; ok(res,await setConfig('formas_pagamento',{formas}))}catch(e){fail(res,e)}});
async function clientesCampanha(publico,cliente_id){ let q=supabase.from('clientes').select('*').neq('bloqueado',true); if(cliente_id) q=q.eq('id',cliente_id); const r=await q.limit(10000); if(r.error) throw r.error; return (r.data||[]).filter(c=>onlyDigits(c.whatsapp||c.telefone).length>=10); }
async function sendWhatsText(numero,msg){ return await evoFetch('/message/sendText/{instance}',{method:'POST',body:JSON.stringify({number:numero,text:msg,options:{delay:1200}})}); }
async function sendWhatsMedia(numero,msg,file){ const media='data:'+file.mimetype+';base64,'+file.buffer.toString('base64'); return await evoFetch('/message/sendMedia/{instance}',{method:'POST',body:JSON.stringify({number:numero,mediatype:file.mimetype.startsWith('video')?'video':'image',mimetype:file.mimetype,caption:msg,media,fileName:file.originalname})}); }
app.post('/api/whatsapp/campanhas/enviar-completo',upload.single('anexo'),async(req,res)=>{try{if(!db(res))return; const body=normalize(req.body||{}); const clientes=await clientesCampanha(body.publico,body.cliente_id); const empresa=await getLogo(); let enviados=0, falhas=0, erros=[]; const msgBase=[body.mensagem||'', empresa.nome?`\n${empresa.nome}`:''].join(''); if(body.enviar_agora==='true'||body.enviar_agora===true){ for(const c of clientes){ const n='55'+onlyDigits(c.whatsapp||c.telefone).replace(/^55/,''); try{ if(req.file) await sendWhatsMedia(n,msgBase,req.file); else await sendWhatsText(n,msgBase); enviados++; }catch(e){ falhas++; erros.push((c.nome||n)+': '+(e.message||e)); } } }
 const campanha={nome:body.nome||'CAMPANHA',mensagem:body.mensagem||'',publico:body.cliente_id?'CLIENTE SELECIONADO':(body.publico||'TODOS'),cliente_id:body.cliente_id||null,status:(body.enviar_agora==='true'||body.enviar_agora===true)?'ENVIADA':'PROGRAMADA',enviados,entregues:0,falhas,agendada_para:body.agendada_para||null,anexo_nome:req.file?.originalname||null,anexo_tipo:req.file?.mimetype||null}; const {data,error}=await supabase.from('campanhas_whatsapp').insert(campanha).select().single(); if(error) throw error; ok(res,{campanha:data,enviados,falhas,erros:erros.slice(0,20),mensagem:`CAMPANHA ${campanha.status}. ENVIADOS: ${enviados} FALHAS: ${falhas}`})}catch(e){fail(res,e)}});


// ===== V5.0 - FORMAS DE PAGAMENTO AVANÇADAS, PEDIDOS COM ITENS E BAIXA EM VENDA =====
function defaultFormasPagamento(){return [
 {nome:'DINHEIRO',tipo:'DESCONTO',percentual:5},
 {nome:'PIX',tipo:'DESCONTO',percentual:5},
 {nome:'CARTÃO DE CRÉDITO',tipo:'JUROS',percentual:15},
 {nome:'CARTÃO DE DÉBITO',tipo:'JUROS',percentual:3},
 {nome:'CHEQUE',tipo:'JUROS',percentual:5}
];}
function normForma(f){
 if(typeof f==='string') return {nome:upper(f),tipo:'NENHUM',percentual:0};
 return {nome:upper(f.nome||f.descricao||'DINHEIRO'),tipo:upper(f.tipo||'NENHUM'),percentual:money(f.percentual||0)};
}
app.get('/api/formas-pagamento-v2',async(_,res)=>{try{if(!db(res))return; const c=await getConfig('formas_pagamento'); let formas=c?.formas||defaultFormasPagamento(); formas=formas.map(normForma); ok(res,formas)}catch(e){fail(res,e)}});
app.post('/api/formas-pagamento-v2',async(req,res)=>{try{if(!db(res))return; let formas=(req.body.formas||[]).map(normForma).filter(f=>f.nome); if(!formas.length) formas=defaultFormasPagamento(); ok(res,await setConfig('formas_pagamento',{formas}))}catch(e){fail(res,e)}});
app.delete('/api/pedido_itens/by-pedido/:id',async(req,res)=>{try{if(!db(res))return; const {error}=await supabase.from('pedido_itens').delete().eq('pedido_id',req.params.id); if(error)throw error; ok(res,{deleted:true})}catch(e){fail(res,e)}});
app.post('/api/pedidos/salvar-completo',async(req,res)=>{try{if(!db(res))return; const body=normalize(req.body||{}); const itens=body.itens||[]; delete body.itens; body.subtotal=money(body.subtotal); body.desconto=money(body.desconto); body.juros=money(body.juros); body.total=money(body.total); const r=await supabase.from('pedidos').upsert(body).select().single(); if(r.error)throw r.error; const pedido=r.data; await supabase.from('pedido_itens').delete().eq('pedido_id',pedido.id); for(const raw of itens){const it=normalize({...raw,pedido_id:pedido.id}); it.quantidade=money(it.quantidade); it.valor_unitario=money(it.valor_unitario); it.total=money(it.total||it.quantidade*it.valor_unitario); const ins=await supabase.from('pedido_itens').insert(it); if(ins.error)throw ins.error;} ok(res,{pedido,itens})}catch(e){fail(res,e)}});
app.post('/api/pedidos/cancelar/:id',async(req,res)=>{try{if(!db(res))return; const b=normalize(req.body||{}); const upd={status:'CANCELADO',motivo_cancelamento:b.motivo||'CANCELADO',multa_cancelamento:money(b.multa_cancelamento||0),cancelada_em:new Date().toISOString()}; const r=await supabase.from('pedidos').update(upd).eq('id',req.params.id).select().single(); if(r.error)throw r.error; if(upd.multa_cancelamento>0){await supabase.from('financeiro').insert({descricao:'MULTA CANCELAMENTO PEDIDO '+req.params.id,tipo:'RECEITA',categoria:'CANCELAMENTO',valor:upd.multa_cancelamento,status:'ABERTO',forma_pagamento:r.data.forma_pagamento||'',observacoes:upd.motivo_cancelamento});} ok(res,r.data)}catch(e){fail(res,e)}});
app.post('/api/pedidos/baixar-venda/:id',async(req,res)=>{try{
  if(!db(res))return;
  const b=normalize(req.body||{});
  const ped=await supabase.from('pedidos').select('*').eq('id',req.params.id).single();
  if(ped.error)throw ped.error;
  if(['BAIXADO/VENDIDO','FINALIZADO'].includes(String(ped.data.status||'').toUpperCase())) throw new Error('Pedido já finalizado.');
  const itens=await supabase.from('pedido_itens').select('*').eq('pedido_id',req.params.id);
  if(itens.error)throw itens.error;
  const vendaBody={cliente_id:ped.data.cliente_id,cliente_nome:ped.data.cliente_nome,subtotal:money(ped.data.subtotal),desconto:money(ped.data.desconto),juros:money(ped.data.juros),total:money(ped.data.total),forma_pagamento:b.forma_pagamento||ped.data.forma_pagamento,status:b.status||'PAGO',observacoes:'BAIXA DO PEDIDO '+req.params.id};
  const venda=await supabase.from('vendas').insert(vendaBody).select().single();
  if(venda.error)throw venda.error;
  for(const it of itens.data||[]){
    const vi={venda_id:venda.data.id,produto_id:it.produto_id,descricao:it.descricao,quantidade:it.quantidade,valor_unitario:it.valor_unitario,total:it.total};
    const ins=await supabase.from('venda_itens').insert(vi); if(ins.error)throw ins.error;
    if(b.baixar_estoque===true||b.baixar_estoque==='true'){
      if(it.produto_id){
        const p=await supabase.from('produtos').select('*').eq('id',it.produto_id).maybeSingle();
        if(!p.error&&p.data){await supabase.from('produtos').update({estoque_atual:money(p.data.estoque_atual)-money(it.quantidade)}).eq('id',it.produto_id); await supabase.from('estoque_movimentos').insert({produto_id:it.produto_id,tipo:'SAÍDA',origem:'VENDA/PEDIDO',quantidade:it.quantidade,valor_unitario:it.valor_unitario,referencia:venda.data.id});}
      } else if(it.receita_id){
        const ri=await supabase.from('receita_itens').select('*').eq('receita_id',it.receita_id);
        if(ri.error)throw ri.error;
        for(const ing of ri.data||[]){
          const qtd=money(ing.quantidade)*money(it.quantidade);
          const p=await supabase.from('produtos').select('*').eq('id',ing.produto_id).maybeSingle();
          if(!p.error&&p.data){await supabase.from('produtos').update({estoque_atual:money(p.data.estoque_atual)-qtd}).eq('id',ing.produto_id); await supabase.from('estoque_movimentos').insert({produto_id:ing.produto_id,tipo:'SAÍDA',origem:'RECEITA/PEDIDO',quantidade:qtd,valor_unitario:ing.custo_unitario,referencia:venda.data.id});}
        }
      }
    }
  }
  await supabase.from('pedidos').update({status:'BAIXADO/VENDIDO',venda_id:venda.data.id,pago_em:new Date().toISOString()}).eq('id',req.params.id);
  ok(res,{venda:venda.data})
}catch(e){fail(res,e)}});



// ===== V5.1 ROTAS EXTRAS: WHATSAPP DESCONECTAR/REENVIAR, XML NF-E E SEED ADMIN =====
app.post('/api/whatsapp/desconectar',async(req,res)=>{try{if(!db(res))return; let msg='SOLICITAÇÃO DE DESCONEXÃO ENVIADA.'; try{await evoFetch('/instance/logout/{instance}',{method:'DELETE'});}catch(e1){try{await evoFetch('/instance/logout/{instance}',{method:'POST'});}catch(e2){try{await evoFetch('/instance/delete/{instance}',{method:'DELETE'});}catch(e3){msg='Configuração mantida. Se a API não desconectar, remova a instância pela Evolution API e gere novo QR.';}}} ok(res,{mensagem:msg})}catch(e){fail(res,e)}});
app.post('/api/whatsapp/campanhas/reenviar/:id',async(req,res)=>{try{if(!db(res))return; const camp=await supabase.from('campanhas_whatsapp').select('*').eq('id',req.params.id).single(); if(camp.error)throw camp.error; const clientes=await clientesCampanha(camp.data.publico||'CLIENTES',camp.data.cliente_id); let enviados=0, falhas=0; for(const c of clientes){const n='55'+onlyDigits(c.whatsapp||c.telefone).replace(/^55/,''); try{await sendWhatsText(n,camp.data.mensagem||''); enviados++;}catch(e){falhas++;}} const upd=await supabase.from('campanhas_whatsapp').update({status:'REENVIADA',enviados:(camp.data.enviados||0)+enviados,falhas:(camp.data.falhas||0)+falhas}).eq('id',req.params.id).select().single(); if(upd.error)throw upd.error; ok(res,{mensagem:`CAMPANHA REENVIADA. Enviados: ${enviados}. Falhas: ${falhas}.`,campanha:upd.data})}catch(e){fail(res,e)}});
function tag(xml,name){const m=xml.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i')); return m?m[1].trim():''}
function cleanXml(v){return String(v||'').replace(/<!\[CDATA\[/g,'').replace(/\]\]>/g,'').trim()}
function detBlocks(xml){return [...xml.matchAll(/<det\b[^>]*>([\s\S]*?)<\/det>/gi)].map(m=>m[1])}
function parseNfeXml(xml){
  const emit=tag(xml,'emit'); const ide=tag(xml,'ide'); const total=tag(xml,'ICMSTot');
  const fornecedor={nome:cleanXml(tag(emit,'xNome')),cnpj:onlyDigits(tag(emit,'CNPJ')),telefone:onlyDigits(tag(emit,'fone')),cidade:cleanXml(tag(tag(emit,'enderEmit'),'xMun')),estado:cleanXml(tag(tag(emit,'enderEmit'),'UF'))};
  const numero_nf=cleanXml(tag(ide,'nNF')); const data_compra=(cleanXml(tag(ide,'dhEmi'))||cleanXml(tag(ide,'dEmi'))||'').slice(0,10); const total_nf=Number(cleanXml(tag(total,'vNF')).replace(',','.'))||0;
  const itens=detBlocks(xml).map(b=>{const prod=tag(b,'prod'); const q=Number(cleanXml(tag(prod,'qCom')).replace(',','.'))||0; const vu=Number(cleanXml(tag(prod,'vUnCom')).replace(',','.'))||0; return {codigo:cleanXml(tag(prod,'cProd')),ean:cleanXml(tag(prod,'cEAN')),nome:cleanXml(tag(prod,'xProd')),ncm:cleanXml(tag(prod,'NCM')),unidade:cleanXml(tag(prod,'uCom'))||'UN',quantidade:q,valor_unitario:vu,total:Number(cleanXml(tag(prod,'vProd')).replace(',','.'))||q*vu};}).filter(i=>i.nome);
  return {fornecedor,numero_nf,data_compra,total_nf,itens};
}
async function sugerirXml(parsed){
  const [forn,prods,cfg]=await Promise.all([supabase.from('fornecedores').select('*'),supabase.from('produtos').select('*'),getConfig('xml_vinculos')]); if(forn.error)throw forn.error; if(prods.error)throw prods.error;
  const vinc=cfg||{fornecedores:{},produtos:{}}; const cnpj=parsed.fornecedor.cnpj; const fSug=vinc.fornecedores?.[cnpj] || (forn.data||[]).find(f=>onlyDigits(f.cnpj||'')===cnpj)?.id || (forn.data||[]).find(f=>upper(f.nome)===upper(parsed.fornecedor.nome))?.id || null; parsed.fornecedor.sugestao_id=fSug;
  parsed.itens=parsed.itens.map(it=>{const key=it.codigo||it.ean||it.nome; const sug=vinc.produtos?.[key] || (prods.data||[]).find(p=>upper(p.nome)===upper(it.nome))?.id || null; return {...it,sugestao_id:sug};}); return parsed;
}
app.post('/api/compras/importar-xml-analisar',upload.single('xml'),async(req,res)=>{try{if(!db(res))return; if(!req.file)throw new Error('Envie o arquivo XML da NF-e.'); const xml=req.file.buffer.toString('utf8'); const parsed=await sugerirXml(parseNfeXml(xml)); ok(res,parsed)}catch(e){fail(res,e)}});
app.post('/api/compras/importar-xml-confirmar',async(req,res)=>{try{if(!db(res))return; const b=normalize(req.body||{}); let fornecedor_id=b.fornecedor_id||null; const vinc=await getConfig('xml_vinculos')||{fornecedores:{},produtos:{}};
  if(!fornecedor_id){const cnpj=onlyDigits(b.fornecedor?.cnpj||''); let existing=null; if(cnpj){const ex=await supabase.from('fornecedores').select('*').eq('cnpj',cnpj).maybeSingle(); if(!ex.error) existing=ex.data;} if(!existing&&b.fornecedor?.nome){const ex=await supabase.from('fornecedores').select('*').ilike('nome',b.fornecedor.nome).maybeSingle(); if(!ex.error) existing=ex.data;} if(existing) fornecedor_id=existing.id; else {const ins=await supabase.from('fornecedores').insert(b.fornecedor).select().single(); if(ins.error)throw ins.error; fornecedor_id=ins.data.id;}}
  if(b.fornecedor?.cnpj) vinc.fornecedores[onlyDigits(b.fornecedor.cnpj)]=fornecedor_id;
  const compra=await supabase.from('compras').insert({fornecedor_id,numero_nf:b.numero_nf,data_compra:b.data_compra,total:0,status:'LANÇADA XML',observacoes:'IMPORTADA POR XML NF-E'}).select().single(); if(compra.error)throw compra.error; let total=0;
  for(const itRaw of b.itens||[]){let it=normalize(itRaw); let produto_id=it.produto_id||null; const key=it.codigo||it.ean||it.nome; if(!produto_id){const ex=await supabase.from('produtos').select('*').ilike('nome',it.nome).maybeSingle(); if(!ex.error&&ex.data) produto_id=ex.data.id; else {const novo=await supabase.from('produtos').insert({nome:it.nome,codigo_barras:it.ean||it.codigo,unidade:it.unidade||'UN',tipo:'INGREDIENTE',custo_unitario:it.valor_unitario,custo_medio:it.valor_unitario,preco_venda:0,estoque_atual:0,estoque_minimo:0,fornecedor_principal:b.fornecedor?.nome||''}).select().single(); if(novo.error)throw novo.error; produto_id=novo.data.id;}}
    if(key) vinc.produtos[key]=produto_id; const qtd=money(it.quantidade), vu=money(it.valor_unitario), itemTotal=money(it.total||qtd*vu); total+=itemTotal; const ci=await supabase.from('compra_itens').insert({compra_id:compra.data.id,produto_id,quantidade:qtd,valor_unitario:vu,total:itemTotal}); if(ci.error)throw ci.error; const p=await supabase.from('produtos').select('*').eq('id',produto_id).single(); if(!p.error){const novoEst=money(p.data.estoque_atual)+qtd; const qtdComp=money(p.data.quantidade_compras)+1; const upd={estoque_atual:novoEst,ultima_compra_valor:vu,ultima_compra_data:b.data_compra||new Date().toISOString().slice(0,10),quantidade_compras:qtdComp,custo_unitario:vu,custo_medio:vu}; await supabase.from('produtos').update(upd).eq('id',produto_id); await supabase.from('estoque_movimentos').insert({produto_id,tipo:'ENTRADA',origem:'XML NF-E',quantidade:qtd,valor_unitario:vu,referencia:compra.data.id});}}
  await supabase.from('compras').update({total}).eq('id',compra.data.id); await setConfig('xml_vinculos',vinc); ok(res,{compra:{...compra.data,total},total})}catch(e){fail(res,e)}});



// ===== V5.4 - IMPORTAÇÃO DE DANFE PDF PARA COMPRAS/PRODUTOS =====
function brNumber(v){return Number(String(v||'0').replace(/\./g,'').replace(',','.'))||0}
function parseDanfePdfText(text){
  const lines=String(text||'').split(/\r?\n/).map(l=>l.trim()).filter(Boolean);
  const all=lines.join('\n');
  const fornecedorNome=(all.match(/Recebemos de\s+(.+?)\s+os produtos/i)||[])[1] || (lines.find(l=>/LTDA|ME|EPP|COMERC/i.test(l))||'FORNECEDOR PDF');
  const cnpj=(all.match(/CNPJ\s*\/\s*CPF\s*\n?\s*([0-9.\/-]{14,20})/i)||all.match(/(\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2})/)||[])[1]||'';
  const nf=(all.match(/N[ºO]?\s*0*([0-9]{3,})/i)||all.match(/Número:\s*([0-9]+)/i)||[])[1]||'';
  const data=(all.match(/Emissão:\s*(\d{2})\/(\d{2})\/(\d{4})/i)||all.match(/DATA DA EMISSÃO\s*\n?\s*(\d{2})\/(\d{2})\/(\d{4})/i)||[]);
  const data_compra=data.length?`${data[3]}-${data[2]}-${data[1]}`:new Date().toISOString().slice(0,10);
  const itens=[];
  const itemRe=/^(\d{1,8})\s+(.+?)\s+(\d{8})\s+\d{3,4}\s+\d{4}\s+([A-Z]{1,3})\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)\s+([\d.,]+)/i;
  for(const l of lines){
    const m=l.match(itemRe);
    if(m){
      itens.push({codigo:m[1], nome:m[2].trim(), ncm:m[3], unidade:m[4], quantidade:brNumber(m[5]), valor_unitario:brNumber(m[6]), desconto:brNumber(m[7]), total:brNumber(m[8])});
    }
  }
  return {fornecedor:{nome:fornecedorNome.trim(),cnpj:cnpj.replace(/\D/g,''),telefone:'',cidade:'',estado:''},numero_nf:nf,data_compra,total_nf:itens.reduce((s,i)=>s+i.total,0),itens};
}
app.post('/api/compras/importar-pdf-analisar',upload.single('pdf'),async(req,res)=>{try{if(!db(res))return; if(!req.file)throw new Error('Envie o PDF/DANFE da NF-e.'); const parsedPdf=await pdfParse(req.file.buffer); const parsed=await sugerirXml(parseDanfePdfText(parsedPdf.text)); ok(res,{...parsed,arquivo:req.file.originalname})}catch(e){fail(res,e)}});



// ===== V5.5 - ROTAS DE REFORÇO PARA RECEITAS/PEDIDOS =====
app.post('/api/receita_itens/salvar',async(req,res)=>{try{if(!db(res))return; const b=normalize(req.body||{}); if(!b.receita_id||!b.produto_id) throw new Error('Informe receita e produto.'); b.quantidade=money(b.quantidade); b.custo_unitario=money(b.custo_unitario); const r=await supabase.from('receita_itens').insert(b).select().single(); if(r.error)throw r.error; ok(res,r.data)}catch(e){fail(res,e)}});
async function baixarEstoqueProduto(produto_id,qtd,origem,referencia,valor_unitario=0){ if(!produto_id||!qtd) return; const p=await supabase.from('produtos').select('*').eq('id',produto_id).maybeSingle(); if(!p.error&&p.data){ await supabase.from('produtos').update({estoque_atual:money(p.data.estoque_atual)-money(qtd)}).eq('id',produto_id); await supabase.from('estoque_movimentos').insert({produto_id,tipo:'SAÍDA',origem,quantidade:qtd,valor_unitario,referencia}); }}

// Fallback SPA compatível com Express 5/path-to-regexp (não usar app.get('*'))
app.use((req,res,next)=>{
  if(req.path.startsWith('/api/')) return next();
  res.sendFile(__dirname+'/public/index.html');
});
app.listen(PORT,()=>console.log('CONFEITARIA OLITECH ERP V5.5 ON '+PORT));
